### ISSUE TITLE
from: can't read /var/mail/jiraone

### ISSUE THREAD

**Issue by aubreyskingdom** [princenyeche/atlassian-cloud-api#40]
When I attempt to run from jiraone import LOGIN, USER and then add my information I am getting an error:

from: can't read /var/mail/jiraone
zsh: command not found: user
zsh: command not found: password
link: =: No such file or directory
zsh: unknown username 'er=u'

**Comment by princenyeche** [comment]
If you have python 3.6.x and above installed, then you will need to be on python shell on your terminal to run that command.
```python
your_user@you~% python
Type "help", "copyright", "credits" or "license" for more information.
>>> from jiraone import LOGIN, USER
>>>
```

**Comment by aubreyskingdom** [comment]
Thanks for the quick response.  If I'm in the python shell I'm still getting an error:
Python 3.9.5 (default, May  3 2021, 19:12:05) 
[Clang 12.0.5 (clang-1205.0.22.9)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> from jiraone import LOGIN, USER
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ModuleNotFoundError: No module named 'jiraone'


So then I thought I should install jiraone within the python shell and this is the result:

>>> pip install jiraone
  File "<stdin>", line 1
    pip install jiraone
        ^
SyntaxError: invalid syntax

**Comment by princenyeche** [comment]
I believe you need to install virtual environment first to do that
```bash
your_user@you~% python -m virtualenv venv
```
cd into the directory of your venv and activate it. You might be asked to upgrade pip and virtualenv, please follow your screen prompt to do that.

```bash
your_user@you~% source venv/bin/activate
(venv)your_user@you~% pip install jiraone
(venv)your_user@you~% python
Type "help", "copyright", "credits" or "license" for more information.
>>>
```

**Comment by princenyeche** [comment]
Hey @aubreyskingdom 
How did your configuration go?

**Comment by aubreyskingdom** [comment]
I've made a lot of progress! I was able to get into the virtual environment successfully and configure my login info.  I am testing the usage of this by running this:
if __name__ == '__main__':
    # the output of the file would be absolute to the directory where this python file is being executed from
    USER.get_all_users(pull="active", user_type="atlassian", file="user_file.csv")

and this is the result I'm getting:
Current Record - At Row 50
Current Record - At Row 100
Current Record - At Row 150
Current Record - At Row 200
Traceback (most recent call last):
  File "<stdin>", line 3, in <module>
  File "/opt/homebrew/lib/python3.9/site-packages/jiraone/reporting.py", line 1139, in get_all_users
    self.report(category=folder, filename=file)
  File "/opt/homebrew/lib/python3.9/site-packages/jiraone/reporting.py", line 1144, in report
    file_writer(folder=category, file_name=filename, data=read, mark="many")
  File "/opt/homebrew/lib/python3.9/site-packages/jiraone/reporting.py", line 1265, in file_writer
    file = path_builder(path=folder, file_name=file_name)
  File "/opt/homebrew/lib/python3.9/site-packages/jiraone/reporting.py", line 1254, in path_builder
    base_dir = os.path.join(WORK_PATH, path)
  File "/opt/homebrew/Cellar/python@3.9/3.9.5/Frameworks/Python.framework/Versions/3.9/lib/python3.9/posixpath.py", line 90, in join
    genericpath._check_arg_types('join', a, *p)
  File "/opt/homebrew/Cellar/python@3.9/3.9.5/Frameworks/Python.framework/Versions/3.9/lib/python3.9/genericpath.py", line 152, in _check_arg_types
    raise TypeError(f'{funcname}() argument must be str, bytes, or '
TypeError: join() argument must be str, bytes, or os.PathLike object, not '_SpecialForm'

**Comment by princenyeche** [comment]
Hey @aubreyskingdom 
I think the problem might be with the path to the file. Can you try the below by adding the `folder` path
```python
USER.get_all_users(pull="active", user_type="atlassian", file="user_file.csv", folder="Test_Folder")
```

**Comment by princenyeche** [comment]
Hi @aubreyskingdom 
Hope the above helps!

**Comment by princenyeche** [comment]
If all is okay, I will be closing off this issue.
